# Generated by Django 5.1.6 on 2025-02-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
