# Generated by Django 5.1.6 on 2025-02-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_medicine_alter_pharmacy_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='pharmacies',
            field=models.ManyToManyField(blank=True, null=True, to='pharmacy.pharmacy'),
        ),
    ]
