# Generated by Django 5.1.6 on 2025-02-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_alter_medicine_pharmacies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='pharmacies',
            field=models.ManyToManyField(related_name='medicines', to='pharmacy.pharmacy'),
        ),
    ]
